project/learnin_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]

project/learning_logs/urls.py
from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('edit_topic/<int:topic_id>/', views.edit_topic, name='edit_topic'),
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

project/users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name = 'register')
]

project/learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
    text = models.CharField(max_length = 200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete = models.CASCADE)

    def __str__(self):
        return self.text;

class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete = models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete = models.CASCADE)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        if len(self.text) <= 50:
            return self.text
        else:
            return f"{self.text[:50]}..."

project/users/models.py
from django.db import models

# Create your models here.

project/learning_logs/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text':'Текст'}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text':''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

project/learning_logs/views.py
from django.shortcuts import render, redirect
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required
from django.http import Http404

# Create your views here.

def index(request):
    return render(request, 'learning_logs\index.html')

@login_required
def topics(request):
    topics = Topic.objects.filter(owner = request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs\\topics.html', context)

@login_required
def topic(request, topic_id):
    topic = Topic.objects.get(id = topic_id)
    if topic.owner != request.user :
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs\\topic.html', context) 

@login_required
def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form =  TopicForm(data = request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')

    context = {"form" : form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def edit_topic(request, topic_id):
    topic = Topic.objects.get(id = topic_id)
    if topic.owner != request.user :
        raise Http404
    if request.method != 'POST':
        form = TopicForm(instance = topic)
    else:
        form =  TopicForm(instance = topic, data = request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topics')

    context = {"topic":topic, "form" : form}
    return render(request, 'learning_logs/edit_topic.html', context)

@login_required
def new_entry(request, topic_id):
    topic = Topic.objects.get(id = topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form =  EntryForm(data = request.POST)
        if form.is_valid():
            new_entry = form.save(commit = False)
            new_entry.topic = topic
            new_entry.owner = request.user
            new_entry.save()
            return redirect('learning_logs:topic', topic_id = topic_id)

    context = {"topic":topic, "form" : form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id = entry_id)
    topic = entry.topic
    if entry.owner != request.user :
        raise Http404
    if request.method != 'POST':
        form = EntryForm(instance = entry)
    else:
        form =  EntryForm(instance = entry, data = request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id = topic.id)

    context = {"entry":entry, "topic":topic, "form" : form}
    return render(request, 'learning_logs/edit_entry.html', context)

project/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data = request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('learning_logs:index')

    context = {'form': form}
    return render(request, 'registration/register.html', context)

project/learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}
<!doctype html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width= device-width, initial-scale=1, shrink-to-fit=no" />
        <title>Тестовый проект на Django</title>

        {% bootstrap_css %}
        {% bootstrap_javascript jquery='full' %}
    </head>

    <body>
        <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
            <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Тестовый проект</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarCollapse" aria-controls="navbarCollapse"
                    aria-expanded="false" aria-label="Переключить навигацию"><span class="navbar-toggler-icon"></span></button>

            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'learning_logs:topics' %}">Список тем</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <span class="navbar-text">Hello, {{user.username}}.</span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        <main role="main" class="container">
            <div class="pb-2 mb-2 border-bottom">
                {% block page_header %}{% endblock page_header %}
            </div>
            <div class="">
                {% block content %}{% endblock content %}
            </div>
        </main>
    </body>
</html>

project/learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h3><a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a></h3>
    <h3>Изменение записи:</h3>
{% endblock page_header %}

{% block content %}
    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-success">Сохранить</button>
        {% endbuttons %}
    </form>
{% endblock content %}

project/learning_logs/templates/learning_logs/edit_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h3>Изменение темы</h3>
{% endblock page_header %}

{% block content %}
    <form action="{% url 'learning_logs:edit_topic' topic.id %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-success">Сохарнить</button>
        {% endbuttons %}
    </form>
{% endblock content %}

project/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
    <div class="jumbotron">
        <h1 class="dicplay-3">Обучение</h1>

        <p class="lead">Этот проект создан в качестве начального. Возможно, он будет раширяться и улучшаться.</p>
        {% if not user.is_authenticated %}
            <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}">Регистрация &raquo;</a>
        {% endif %}
    </div>
{% endblock page_header %}

project/learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h3><a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a></h3>
    <h3>Добавление новой записи:</h3>
{% endblock page_header %}

{% block content %}
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-success">Добавить</button>
        {% endbuttons %}
    </form>
{% endblock content %}

project/learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h3>Добавление новой темы</h3>
{% endblock page_header %}

{% block content %}
    <form action="{% url 'learning_logs:new_topic' %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-success">Добавить</button>
        {% endbuttons %}
    </form>
{% endblock content %}

project/learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}


{% block page_header %}
    <h3>Записи темы "{{topic}}":</h3>
{% endblock page_header %}

{% block content %}
    <h3>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">Добавить новую запись</a>
    </h3>
    <ul>
        {% for entry in entries %}
            <div class="card mb-3">
                <h4 class="card-header">
                    {{entry.date_added|date:'M d, Y H:i'}}
                    <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">Изменить запись</a></small>
                </h4>
                <div class="card-body">
                    {{entry.text|linebreaks}}
                </div>
            </div>
        {% empty %}
            <p>Нет данных для отображения</p>
        {% endfor %}
    </ul>

{% endblock content %}

project/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}


{% block page_header %}
    <h2>Темы</h2>
{% endblock page_header %}
{% block content %}
    <ul>
        {% for topic in topics %}
        <li> 
            <h3>
                <a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a>
                <a class="btn btn-sm btn btn-light btn-circle" href="{% url 'learning_logs:edit_topic' topic.id %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
                    <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z" />
                    </svg>
                </a>
            </h3>
        </li>
        {% empty %}
        <li><h3>Нет данных для отображения</h3></li>
        {% endfor %}
    </ul>
    <h3><a href="{% url 'learning_logs:new_topic' %}">Добавить новую тему</a></h3>

{% endblock content %}